# Site settings
title: Aristocat-A
email: angela.aeschbach@gmail.com
url: https://aristocat-a.github.io
description: "This is my portfolio."
keywords: "portfolio, data science, bioinformatics, data visualization"
skills: "Bioinformatician - Data Scientist"
meta_author: A Aristocat

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5f83a7
  primary-rgb: "95, 131, 167"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Aristocat A
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: github
    url: http://github.com/aristocat-a

# Postal address (add as many lines as necessary)
address:
  - line: Zurich, Switzerland

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
